/* Generated By:JJTree&JavaCC: Do not edit this line. Parser.java */
package javaCC;

import java.util.List;

public class Parser/*@bgen(jjtree)*/implements ParserTreeConstants, ParserConstants {/*@bgen(jjtree)*/
  protected static JJTParserState jjtree = new JJTParserState();
        private static final Integer SUCESSO = 1;
        private static final Integer ERRO = 0;

        private static List<Tok> listaTokens;

        public SimpleNode compilar() throws ParseException, Error {
                return Parser.program();
        }

  static final public SimpleNode program() throws ParseException {
 /*@bgen(jjtree) program */
  SimpleNode jjtn000 = new SimpleNode(JJTPROGRAM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      decSeqList();
                 jjtree.closeNodeScope(jjtn000, true);
                 jjtc000 = false;
                 {if (true) return jjtn000;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public void decSeqList() throws ParseException {
 /*@bgen(jjtree) decSeqList */
  SimpleNode jjtn000 = new SimpleNode(JJTDECSEQLIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
      case INT:
      case BOOL:
        type();
        IDENTIFICADOR();
        decSeq();
        break;
      case IDENTIFICADOR:
        decProcedimento();
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void decSeq() throws ParseException {
 /*@bgen(jjtree) decSeq */
  SimpleNode jjtn000 = new SimpleNode(JJTDECSEQ);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ACOLCH:
      case VIRGULA:
      case PTOVIRGULA:
      case ATRIBUICAO:
        decVar();
        break;
      case APARENT:
        decFuncao();
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void decProcedimento() throws ParseException {
 /*@bgen(jjtree) decProcedimento */
  SimpleNode jjtn000 = new SimpleNode(JJTDECPROCEDIMENTO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      IDENTIFICADOR();
      decFuncao();
                                jjtree.closeNodeScope(jjtn000, true);
                                jjtc000 = false;
                                listaTokens.add(Tok.IDENTIFICADOR);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void decFuncao() throws ParseException {
 /*@bgen(jjtree) decFuncao */
  SimpleNode jjtn000 = new SimpleNode(JJTDECFUNCAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      APARENT();
      listaParametros();
      FPARENT();
      ACHAVE();
      bloco();
      FCHAVE();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void decVar() throws ParseException {
 /*@bgen(jjtree) decVar */
  SimpleNode jjtn000 = new SimpleNode(JJTDECVAR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      dec();
      PTOVIRGULA();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void dec() throws ParseException {
 /*@bgen(jjtree) dec */
  SimpleNode jjtn000 = new SimpleNode(JJTDEC);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ATRIBUICAO:
        atribuicao();
        break;
      case ACOLCH:
        ACOLCH();
        NUMERO();
        FCOLCH();
        decLinha();
        break;
      case VIRGULA:
        VIRGULA();
        IDENTIFICADOR();
        dec();
        break;
      default:
        jj_la1[2] = jj_gen;
        empty();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void decLinha() throws ParseException {
 /*@bgen(jjtree) decLinha */
  SimpleNode jjtn000 = new SimpleNode(JJTDECLINHA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ATRIBUICAO:
        atribuicao();
        break;
      default:
        jj_la1[3] = jj_gen;
        empty();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void atribuicao() throws ParseException {
 /*@bgen(jjtree) atribuicao */
  SimpleNode jjtn000 = new SimpleNode(JJTATRIBUICAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      ATRIBUICAO();
      literal();
      dec();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void listaParametros() throws ParseException {
 /*@bgen(jjtree) listaParametros */
  SimpleNode jjtn000 = new SimpleNode(JJTLISTAPARAMETROS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
      case INT:
      case BOOL:
        type();
        IDENTIFICADOR();
        restoParametros();
        break;
      default:
        jj_la1[4] = jj_gen;
        empty();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void restoParametros() throws ParseException {
 /*@bgen(jjtree) restoParametros */
  SimpleNode jjtn000 = new SimpleNode(JJTRESTOPARAMETROS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRGULA:
        VIRGULA();
        type();
        IDENTIFICADOR();
        restoParametros();
        break;
      default:
        jj_la1[5] = jj_gen;
        listaParametros();
      }
    } catch (Throwable jjte000) {
   if (jjtc000) {
     jjtree.clearNodeScope(jjtn000);
     jjtc000 = false;
   } else {
     jjtree.popNode();
   }
   if (jjte000 instanceof RuntimeException) {
     {if (true) throw (RuntimeException)jjte000;}
   }
   if (jjte000 instanceof ParseException) {
     {if (true) throw (ParseException)jjte000;}
   }
   {if (true) throw (Error)jjte000;}
    } finally {
   if (jjtc000) {
     jjtree.closeNodeScope(jjtn000, true);
   }
    }
  }

  static final public void type() throws ParseException {
 /*@bgen(jjtree) type */
  SimpleNode jjtn000 = new SimpleNode(JJTTYPE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
        INT();
        break;
      case STRING:
        STRING();
        break;
      case BOOL:
        BOOL();
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void bloco() throws ParseException {
 /*@bgen(jjtree) bloco */
  SimpleNode jjtn000 = new SimpleNode(JJTBLOCO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
      case INT:
      case BOOL:
        type();
        IDENTIFICADOR();
        decVar();
        listaEstado();
        break;
      default:
        jj_la1[7] = jj_gen;
        listaEstado();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void listaEstado() throws ParseException {
 /*@bgen(jjtree) listaEstado */
  SimpleNode jjtn000 = new SimpleNode(JJTLISTAESTADO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFICADOR:
        IDENTIFICADOR();
        subRotinaAtribuicao();
        break;
      case IF:
        chamadaIf();
        break;
      case WHILE:
        chamadaWhile();
        break;
      case FOR:
        chamadaFor();
        break;
      case BREAK:
        chamadaBreak();
        break;
      case RETURN:
        chamadaReturn();
        break;
      case READ:
        chamadaRead();
        break;
      case WRITE:
        chamadaWrite();
        break;
      default:
        jj_la1[8] = jj_gen;
        empty();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void subRotinaAtribuicao() throws ParseException {
 /*@bgen(jjtree) subRotinaAtribuicao */
  SimpleNode jjtn000 = new SimpleNode(JJTSUBROTINAATRIBUICAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case APARENT:
        chamadaSubRotina();
        PTOVIRGULA();
        break;
      case ATRIBUICAO:
      case ATRIBUICAO_SOMA:
      case ATRIBUICAO_SUB:
      case ATRIBUICAO_MUL:
      case ATRIBUICAO_DIV:
      case MOD:
        chamadaAtribuicao();
        PTOVIRGULA();
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void chamadaRead() throws ParseException {
 /*@bgen(jjtree) chamadaRead */
  SimpleNode jjtn000 = new SimpleNode(JJTCHAMADAREAD);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      READ();
      var();
      PTOVIRGULA();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void var() throws ParseException {
 /*@bgen(jjtree) var */
  SimpleNode jjtn000 = new SimpleNode(JJTVAR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      IDENTIFICADOR();
      varLinha();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void varLinha() throws ParseException {
 /*@bgen(jjtree) varLinha */
  SimpleNode jjtn000 = new SimpleNode(JJTVARLINHA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ACOLCH:
        ACOLCH();
        exp();
        FCOLCH();
        break;
      default:
        jj_la1[10] = jj_gen;
        empty();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void chamadaWrite() throws ParseException {
 /*@bgen(jjtree) chamadaWrite */
  SimpleNode jjtn000 = new SimpleNode(JJTCHAMADAWRITE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      WRITE();
      listaArgumento();
      PTOVIRGULA();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void chamadaReturn() throws ParseException {
 /*@bgen(jjtree) chamadaReturn */
  SimpleNode jjtn000 = new SimpleNode(JJTCHAMADARETURN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      RETURN();
      chamadaReturnLinha();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void chamadaReturnLinha() throws ParseException {
 /*@bgen(jjtree) chamadaReturnLinha */
  SimpleNode jjtn000 = new SimpleNode(JJTCHAMADARETURNLINHA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PTOVIRGULA:
        PTOVIRGULA();
        break;
      case APARENT:
      case SUB:
      case NOT:
      case TRUE:
      case FALSE:
      case NUMERO:
      case IDENTIFICADOR:
        exp();
        PTOVIRGULA();
        break;
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void chamadaBreak() throws ParseException {
 /*@bgen(jjtree) chamadaBreak */
  SimpleNode jjtn000 = new SimpleNode(JJTCHAMADABREAK);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      BREAK();
      PTOVIRGULA();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void chamadaFor() throws ParseException {
 /*@bgen(jjtree) chamadaFor */
  SimpleNode jjtn000 = new SimpleNode(JJTCHAMADAFOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      FOR();
      APARENT();
      IDENTIFICADOR();
      chamadaAtribuicao();
      PTOVIRGULA();
      exp();
      PTOVIRGULA();
      IDENTIFICADOR();
      chamadaAtribuicao();
      FPARENT();
      ACHAVE();
      bloco();
      FCHAVE();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void chamadaWhile() throws ParseException {
 /*@bgen(jjtree) chamadaWhile */
  SimpleNode jjtn000 = new SimpleNode(JJTCHAMADAWHILE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      WHILE();
      APARENT();
      exp();
      FPARENT();
      ACHAVE();
      bloco();
      FCHAVE();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void chamadaIf() throws ParseException {
 /*@bgen(jjtree) chamadaIf */
  SimpleNode jjtn000 = new SimpleNode(JJTCHAMADAIF);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      IF();
      APARENT();
      exp();
      FPARENT();
      ACHAVE();
      bloco();
      FCHAVE();
      chamadaIfLinha();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void chamadaIfLinha() throws ParseException {
 /*@bgen(jjtree) chamadaIfLinha */
  SimpleNode jjtn000 = new SimpleNode(JJTCHAMADAIFLINHA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ELSE:
        ELSE();
        ACHAVE();
        bloco();
        FCHAVE();
        break;
      default:
        jj_la1[12] = jj_gen;
        empty();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void chamadaSubRotina() throws ParseException {
 /*@bgen(jjtree) chamadaSubRotina */
  SimpleNode jjtn000 = new SimpleNode(JJTCHAMADASUBROTINA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      APARENT();
      listaArgumento();
      FPARENT();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void chamadaAtribuicao() throws ParseException {
 /*@bgen(jjtree) chamadaAtribuicao */
  SimpleNode jjtn000 = new SimpleNode(JJTCHAMADAATRIBUICAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ATRIBUICAO:
        ATRIBUICAO();
        exp();
        break;
      case ATRIBUICAO_SOMA:
        ATRIBUICAO_SOMA();
        exp();
        break;
      case ATRIBUICAO_SUB:
        ATRIBUICAO_SUB();
        exp();
        break;
      case ATRIBUICAO_MUL:
        ATRIBUICAO_MUL();
        exp();
        break;
      case ATRIBUICAO_DIV:
        ATRIBUICAO_DIV();
        exp();
        break;
      case MOD:
        MOD();
        exp();
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void exp() throws ParseException {
 /*@bgen(jjtree) exp */
  SimpleNode jjtn000 = new SimpleNode(JJTEXP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TRUE:
      case FALSE:
      case NUMERO:
      case IDENTIFICADOR:
        literal();
        expLinha();
        break;
      case NOT:
        NOT();
        exp();
        expLinha();
        break;
      case SUB:
        SUB();
        exp();
        expLinha();
        break;
      case APARENT:
        APARENT();
        exp();
        FPARENT();
        expLinha();
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void listaArgumento() throws ParseException {
 /*@bgen(jjtree) listaArgumento */
  SimpleNode jjtn000 = new SimpleNode(JJTLISTAARGUMENTO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFICADOR:
        IDENTIFICADOR();
        restoArgumentos();
        break;
      case NUMERO:
        NUMERO();
        restoArgumentos();
        break;
      default:
        jj_la1[15] = jj_gen;
        empty();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void restoArgumentos() throws ParseException {
 /*@bgen(jjtree) restoArgumentos */
  SimpleNode jjtn000 = new SimpleNode(JJTRESTOARGUMENTOS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRGULA:
        VIRGULA();
        restoArgumentosLinha();
        break;
      default:
        jj_la1[16] = jj_gen;
        listaArgumento();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void restoArgumentosLinha() throws ParseException {
 /*@bgen(jjtree) restoArgumentosLinha */
  SimpleNode jjtn000 = new SimpleNode(JJTRESTOARGUMENTOSLINHA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFICADOR:
        IDENTIFICADOR();
        restoArgumentos();
        break;
      case NUMERO:
        NUMERO();
        restoArgumentos();
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void literal() throws ParseException {
 /*@bgen(jjtree) literal */
  SimpleNode jjtn000 = new SimpleNode(JJTLITERAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUMERO:
        NUMERO();
        break;
      case IDENTIFICADOR:
        IDENTIFICADOR();
        chamaFuncao();
        break;
      case TRUE:
        TRUE();
        break;
      case FALSE:
        FALSE();
        break;
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void chamaFuncao() throws ParseException {
 /*@bgen(jjtree) chamaFuncao */
  SimpleNode jjtn000 = new SimpleNode(JJTCHAMAFUNCAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case APARENT:
        chamadaSubRotina();
        break;
      default:
        jj_la1[19] = jj_gen;
        empty();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void expLinha() throws ParseException {
 /*@bgen(jjtree) expLinha */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPLINHA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOMA:
        SOMA();
        exp();
        expLinha();
        break;
      case SUB:
        SUB();
        exp();
        expLinha();
        break;
      case MUL:
        MUL();
        exp();
        expLinha();
        break;
      case DIV:
        DIV();
        exp();
        expLinha();
        break;
      case RESTO:
        RESTO();
        exp();
        expLinha();
        break;
      case IGUAL:
        IGUAL();
        exp();
        expLinha();
        break;
      case DIFERENTE:
        DIFERENTE();
        exp();
        expLinha();
        break;
      case MAIORIGUAL:
        MAIORIGUAL();
        exp();
        expLinha();
        break;
      case MENORIGUAL:
        MENORIGUAL();
        exp();
        expLinha();
        break;
      case MAIOR:
        MAIOR();
        exp();
        expLinha();
        break;
      case MENOR:
        MENOR();
        exp();
        expLinha();
        break;
      case OR:
        OR();
        exp();
        expLinha();
        break;
      case AND:
        AND();
        exp();
        expLinha();
        break;
      case TERN_ENTAO:
        TERN_ENTAO();
        exp();
        TERN_SENAO();
        exp();
        expLinha();
        break;
      default:
        jj_la1[20] = jj_gen;
        empty();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void empty() throws ParseException {
 /*@bgen(jjtree) empty */
  SimpleNode jjtn000 = new SimpleNode(JJTEMPTY);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;

    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void APARENT() throws ParseException {
                                   /*@bgen(jjtree) APARENT */
  SimpleNode jjtn000 = new SimpleNode(JJTAPARENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(APARENT);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void FPARENT() throws ParseException {
                                   /*@bgen(jjtree) FPARENT */
  SimpleNode jjtn000 = new SimpleNode(JJTFPARENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FPARENT);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void ACOLCH() throws ParseException {
                                   /*@bgen(jjtree) ACOLCH */
  SimpleNode jjtn000 = new SimpleNode(JJTACOLCH);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ACOLCH);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void FCOLCH() throws ParseException {
                                   /*@bgen(jjtree) FCOLCH */
  SimpleNode jjtn000 = new SimpleNode(JJTFCOLCH);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FCOLCH);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void ACHAVE() throws ParseException {
                                   /*@bgen(jjtree) ACHAVE */
  SimpleNode jjtn000 = new SimpleNode(JJTACHAVE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ACHAVE);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void FCHAVE() throws ParseException {
                                   /*@bgen(jjtree) FCHAVE */
  SimpleNode jjtn000 = new SimpleNode(JJTFCHAVE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FCHAVE);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void VIRGULA() throws ParseException {
                                   /*@bgen(jjtree) VIRGULA */
  SimpleNode jjtn000 = new SimpleNode(JJTVIRGULA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(VIRGULA);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void PTOVIRGULA() throws ParseException {
                                   /*@bgen(jjtree) PTOVIRGULA */
  SimpleNode jjtn000 = new SimpleNode(JJTPTOVIRGULA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(PTOVIRGULA);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void SOMA() throws ParseException {
                                   /*@bgen(jjtree) SOMA */
  SimpleNode jjtn000 = new SimpleNode(JJTSOMA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(SOMA);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void SUB() throws ParseException {
                                           /*@bgen(jjtree) SUB */
  SimpleNode jjtn000 = new SimpleNode(JJTSUB);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(SUB);
    } finally {
                                                 if (jjtc000) {
                                                   jjtree.closeNodeScope(jjtn000, true);
                                                 }
    }
  }

  static final public void MUL() throws ParseException {
                                           /*@bgen(jjtree) MUL */
  SimpleNode jjtn000 = new SimpleNode(JJTMUL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MUL);
    } finally {
                                                 if (jjtc000) {
                                                   jjtree.closeNodeScope(jjtn000, true);
                                                 }
    }
  }

  static final public void DIV() throws ParseException {
                                           /*@bgen(jjtree) DIV */
  SimpleNode jjtn000 = new SimpleNode(JJTDIV);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(DIV);
    } finally {
                                                 if (jjtc000) {
                                                   jjtree.closeNodeScope(jjtn000, true);
                                                 }
    }
  }

  static final public void IGUAL() throws ParseException {
                                   /*@bgen(jjtree) IGUAL */
  SimpleNode jjtn000 = new SimpleNode(JJTIGUAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(IGUAL);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void DIFERENTE() throws ParseException {
                                   /*@bgen(jjtree) DIFERENTE */
  SimpleNode jjtn000 = new SimpleNode(JJTDIFERENTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(DIFERENTE);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void MAIOR() throws ParseException {
                                   /*@bgen(jjtree) MAIOR */
  SimpleNode jjtn000 = new SimpleNode(JJTMAIOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MAIOR);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void MAIORIGUAL() throws ParseException {
                                   /*@bgen(jjtree) MAIORIGUAL */
  SimpleNode jjtn000 = new SimpleNode(JJTMAIORIGUAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MAIORIGUAL);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void MENOR() throws ParseException {
                                   /*@bgen(jjtree) MENOR */
  SimpleNode jjtn000 = new SimpleNode(JJTMENOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MENOR);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void MENORIGUAL() throws ParseException {
                                   /*@bgen(jjtree) MENORIGUAL */
  SimpleNode jjtn000 = new SimpleNode(JJTMENORIGUAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MENORIGUAL);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void OR() throws ParseException {
                                           /*@bgen(jjtree) OR */
  SimpleNode jjtn000 = new SimpleNode(JJTOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(OR);
    } finally {
                                                 if (jjtc000) {
                                                   jjtree.closeNodeScope(jjtn000, true);
                                                 }
    }
  }

  static final public void AND() throws ParseException {
                                           /*@bgen(jjtree) AND */
  SimpleNode jjtn000 = new SimpleNode(JJTAND);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(AND);
    } finally {
                                                 if (jjtc000) {
                                                   jjtree.closeNodeScope(jjtn000, true);
                                                 }
    }
  }

  static final public void NOT() throws ParseException {
                                           /*@bgen(jjtree) NOT */
  SimpleNode jjtn000 = new SimpleNode(JJTNOT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(NOT);
    } finally {
                                                 if (jjtc000) {
                                                   jjtree.closeNodeScope(jjtn000, true);
                                                 }
    }
  }

  static final public void ATRIBUICAO() throws ParseException {
                                   /*@bgen(jjtree) ATRIBUICAO */
  SimpleNode jjtn000 = new SimpleNode(JJTATRIBUICAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ATRIBUICAO);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void ATRIBUICAO_SOMA() throws ParseException {
                           /*@bgen(jjtree) ATRIBUICAO_SOMA */
  SimpleNode jjtn000 = new SimpleNode(JJTATRIBUICAO_SOMA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ATRIBUICAO_SOMA);
    } finally {
                                 if (jjtc000) {
                                   jjtree.closeNodeScope(jjtn000, true);
                                 }
    }
  }

  static final public void ATRIBUICAO_SUB() throws ParseException {
                           /*@bgen(jjtree) ATRIBUICAO_SUB */
  SimpleNode jjtn000 = new SimpleNode(JJTATRIBUICAO_SUB);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ATRIBUICAO_SUB);
    } finally {
                                 if (jjtc000) {
                                   jjtree.closeNodeScope(jjtn000, true);
                                 }
    }
  }

  static final public void ATRIBUICAO_MUL() throws ParseException {
                           /*@bgen(jjtree) ATRIBUICAO_MUL */
  SimpleNode jjtn000 = new SimpleNode(JJTATRIBUICAO_MUL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ATRIBUICAO_MUL);
    } finally {
                                 if (jjtc000) {
                                   jjtree.closeNodeScope(jjtn000, true);
                                 }
    }
  }

  static final public void ATRIBUICAO_DIV() throws ParseException {
                           /*@bgen(jjtree) ATRIBUICAO_DIV */
  SimpleNode jjtn000 = new SimpleNode(JJTATRIBUICAO_DIV);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ATRIBUICAO_DIV);
    } finally {
                                 if (jjtc000) {
                                   jjtree.closeNodeScope(jjtn000, true);
                                 }
    }
  }

  static final public void MOD() throws ParseException {
                                           /*@bgen(jjtree) MOD */
  SimpleNode jjtn000 = new SimpleNode(JJTMOD);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MOD);
    } finally {
                                                 if (jjtc000) {
                                                   jjtree.closeNodeScope(jjtn000, true);
                                                 }
    }
  }

  static final public void TERN_ENTAO() throws ParseException {
                                   /*@bgen(jjtree) TERN_ENTAO */
  SimpleNode jjtn000 = new SimpleNode(JJTTERN_ENTAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(TERN_ENTAO);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void TERN_SENAO() throws ParseException {
                                   /*@bgen(jjtree) TERN_SENAO */
  SimpleNode jjtn000 = new SimpleNode(JJTTERN_SENAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(TERN_SENAO);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void INT() throws ParseException {
                                           /*@bgen(jjtree) INT */
  SimpleNode jjtn000 = new SimpleNode(JJTINT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(INT);
    } finally {
                                                 if (jjtc000) {
                                                   jjtree.closeNodeScope(jjtn000, true);
                                                 }
    }
  }

  static final public void BOOL() throws ParseException {
                                   /*@bgen(jjtree) BOOL */
  SimpleNode jjtn000 = new SimpleNode(JJTBOOL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(BOOL);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void TRUE() throws ParseException {
                                   /*@bgen(jjtree) TRUE */
  SimpleNode jjtn000 = new SimpleNode(JJTTRUE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(TRUE);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void FALSE() throws ParseException {
                                   /*@bgen(jjtree) FALSE */
  SimpleNode jjtn000 = new SimpleNode(JJTFALSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FALSE);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void BREAK() throws ParseException {
                                   /*@bgen(jjtree) BREAK */
  SimpleNode jjtn000 = new SimpleNode(JJTBREAK);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(BREAK);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void FOR() throws ParseException {
                                           /*@bgen(jjtree) FOR */
  SimpleNode jjtn000 = new SimpleNode(JJTFOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FOR);
    } finally {
                                                 if (jjtc000) {
                                                   jjtree.closeNodeScope(jjtn000, true);
                                                 }
    }
  }

  static final public void WHILE() throws ParseException {
                                   /*@bgen(jjtree) WHILE */
  SimpleNode jjtn000 = new SimpleNode(JJTWHILE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(WHILE);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void RETURN() throws ParseException {
                                   /*@bgen(jjtree) RETURN */
  SimpleNode jjtn000 = new SimpleNode(JJTRETURN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(RETURN);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void IF() throws ParseException {
                                           /*@bgen(jjtree) IF */
  SimpleNode jjtn000 = new SimpleNode(JJTIF);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(IF);
    } finally {
                                                 if (jjtc000) {
                                                   jjtree.closeNodeScope(jjtn000, true);
                                                 }
    }
  }

  static final public void ELSE() throws ParseException {
                                   /*@bgen(jjtree) ELSE */
  SimpleNode jjtn000 = new SimpleNode(JJTELSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ELSE);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void RESTO() throws ParseException {
                                   /*@bgen(jjtree) RESTO */
  SimpleNode jjtn000 = new SimpleNode(JJTRESTO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(RESTO);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void READ() throws ParseException {
                                   /*@bgen(jjtree) READ */
  SimpleNode jjtn000 = new SimpleNode(JJTREAD);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(READ);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void WRITE() throws ParseException {
                                   /*@bgen(jjtree) WRITE */
  SimpleNode jjtn000 = new SimpleNode(JJTWRITE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(WRITE);
    } finally {
                                         if (jjtc000) {
                                           jjtree.closeNodeScope(jjtn000, true);
                                         }
    }
  }

  static final public void STRING() throws ParseException {
                                   /*@bgen(jjtree) STRING */
                                    SimpleNode jjtn000 = new SimpleNode(JJTSTRING);
                                    boolean jjtc000 = true;
                                    jjtree.openNodeScope(jjtn000);Token str;
    try {
      str = jj_consume_token(STRING);
                                                                      jjtree.closeNodeScope(jjtn000, true);
                                                                      jjtc000 = false;
                                                                      jjtn000.value = str.image;
    } finally {
                                                     if (jjtc000) {
                                                       jjtree.closeNodeScope(jjtn000, true);
                                                     }
    }
  }

  static final public void NUMERO() throws ParseException {
                                   /*@bgen(jjtree) NUMERO */
                                    SimpleNode jjtn000 = new SimpleNode(JJTNUMERO);
                                    boolean jjtc000 = true;
                                    jjtree.openNodeScope(jjtn000);Token num;
    try {
      num = jj_consume_token(NUMERO);
                                                                      jjtree.closeNodeScope(jjtn000, true);
                                                                      jjtc000 = false;
                                                                      jjtn000.value = num.image;
    } finally {
                                                     if (jjtc000) {
                                                       jjtree.closeNodeScope(jjtn000, true);
                                                     }
    }
  }

  static final public void IDENTIFICADOR() throws ParseException {
                           /*@bgen(jjtree) IDENTIFICADOR */
                            SimpleNode jjtn000 = new SimpleNode(JJTIDENTIFICADOR);
                            boolean jjtc000 = true;
                            jjtree.openNodeScope(jjtn000);Token id;
    try {
      id = jj_consume_token(IDENTIFICADOR);
                                                                    jjtree.closeNodeScope(jjtn000, true);
                                                                    jjtc000 = false;
                                                                    jjtn000.value = id.image;
    } finally {
                                             if (jjtc000) {
                                               jjtree.closeNodeScope(jjtn000, true);
                                             }
    }
  }

  static final public Tok teste_lexico() throws ParseException {
 /*@bgen(jjtree) teste_lexico */
  SimpleNode jjtn000 = new SimpleNode(JJTTESTE_LEXICO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case APARENT:
        APARENT();
              jjtree.closeNodeScope(jjtn000, true);
              jjtc000 = false;
              {if (true) return Tok.APARENT;}
        break;
      case FPARENT:
        FPARENT();
              jjtree.closeNodeScope(jjtn000, true);
              jjtc000 = false;
              {if (true) return Tok.FPARENT;}
        break;
      case ACOLCH:
        ACOLCH();
             jjtree.closeNodeScope(jjtn000, true);
             jjtc000 = false;
             {if (true) return Tok.ACOLCH;}
        break;
      case FCOLCH:
        FCOLCH();
             jjtree.closeNodeScope(jjtn000, true);
             jjtc000 = false;
             {if (true) return Tok.FCOLCH;}
        break;
      case ACHAVE:
        ACHAVE();
             jjtree.closeNodeScope(jjtn000, true);
             jjtc000 = false;
             {if (true) return Tok.ACHAVE;}
        break;
      case FCHAVE:
        FCHAVE();
             jjtree.closeNodeScope(jjtn000, true);
             jjtc000 = false;
             {if (true) return Tok.FCHAVE;}
        break;
      case VIRGULA:
        VIRGULA();
              jjtree.closeNodeScope(jjtn000, true);
              jjtc000 = false;
              {if (true) return Tok.VIRGULA;}
        break;
      case PTOVIRGULA:
        PTOVIRGULA();
                 jjtree.closeNodeScope(jjtn000, true);
                 jjtc000 = false;
                 {if (true) return Tok.PTOVIRGULA;}
        break;
      case SOMA:
        SOMA();
           jjtree.closeNodeScope(jjtn000, true);
           jjtc000 = false;
           {if (true) return Tok.SOMA;}
        break;
      case SUB:
        SUB();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          {if (true) return Tok.SUB;}
        break;
      case MUL:
        MUL();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          {if (true) return Tok.MUL;}
        break;
      case DIV:
        DIV();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          {if (true) return Tok.DIV;}
        break;
      case IGUAL:
        IGUAL();
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {if (true) return Tok.IGUAL;}
        break;
      case DIFERENTE:
        DIFERENTE();
                jjtree.closeNodeScope(jjtn000, true);
                jjtc000 = false;
                {if (true) return Tok.DIFERENTE;}
        break;
      case MAIOR:
        MAIOR();
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {if (true) return Tok.MAIOR;}
        break;
      case MAIORIGUAL:
        MAIORIGUAL();
                 jjtree.closeNodeScope(jjtn000, true);
                 jjtc000 = false;
                 {if (true) return Tok.MAIORIGUAL;}
        break;
      case MENOR:
        MENOR();
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {if (true) return Tok.MENOR;}
        break;
      case MENORIGUAL:
        MENORIGUAL();
                 jjtree.closeNodeScope(jjtn000, true);
                 jjtc000 = false;
                 {if (true) return Tok.MENORIGUAL;}
        break;
      case OR:
        OR();
         jjtree.closeNodeScope(jjtn000, true);
         jjtc000 = false;
         {if (true) return Tok.OR;}
        break;
      case AND:
        AND();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          {if (true) return Tok.AND;}
        break;
      case NOT:
        NOT();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          {if (true) return Tok.NOT;}
        break;
      case ATRIBUICAO:
        ATRIBUICAO();
                 jjtree.closeNodeScope(jjtn000, true);
                 jjtc000 = false;
                 {if (true) return Tok.ATRIBUICAO;}
        break;
      case ATRIBUICAO_SOMA:
        ATRIBUICAO_SOMA();
                      jjtree.closeNodeScope(jjtn000, true);
                      jjtc000 = false;
                      {if (true) return Tok.ATRIBUICAO_SOMA;}
        break;
      case ATRIBUICAO_SUB:
        ATRIBUICAO_SUB();
                     jjtree.closeNodeScope(jjtn000, true);
                     jjtc000 = false;
                     {if (true) return Tok.ATRIBUICAO_SUB;}
        break;
      case ATRIBUICAO_MUL:
        ATRIBUICAO_MUL();
                     jjtree.closeNodeScope(jjtn000, true);
                     jjtc000 = false;
                     {if (true) return Tok.ATRIBUICAO_MUL;}
        break;
      case ATRIBUICAO_DIV:
        ATRIBUICAO_DIV();
                     jjtree.closeNodeScope(jjtn000, true);
                     jjtc000 = false;
                     {if (true) return Tok.ATRIBUICAO_DIV;}
        break;
      case MOD:
        MOD();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          {if (true) return Tok.MOD;}
        break;
      case TERN_ENTAO:
        TERN_ENTAO();
                 jjtree.closeNodeScope(jjtn000, true);
                 jjtc000 = false;
                 {if (true) return Tok.TERN_ENTAO;}
        break;
      case TERN_SENAO:
        TERN_SENAO();
                 jjtree.closeNodeScope(jjtn000, true);
                 jjtc000 = false;
                 {if (true) return Tok.TERN_SENAO;}
        break;
      case INT:
        INT();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          {if (true) return Tok.INT;}
        break;
      case BOOL:
        BOOL();
           jjtree.closeNodeScope(jjtn000, true);
           jjtc000 = false;
           {if (true) return Tok.BOOL;}
        break;
      case TRUE:
        TRUE();
           jjtree.closeNodeScope(jjtn000, true);
           jjtc000 = false;
           {if (true) return Tok.TRUE;}
        break;
      case FALSE:
        FALSE();
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {if (true) return Tok.FALSE;}
        break;
      case BREAK:
        BREAK();
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {if (true) return Tok.BREAK;}
        break;
      case FOR:
        FOR();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          {if (true) return Tok.FOR;}
        break;
      case WHILE:
        WHILE();
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {if (true) return Tok.WHILE;}
        break;
      case RETURN:
        RETURN();
             jjtree.closeNodeScope(jjtn000, true);
             jjtc000 = false;
             {if (true) return Tok.RETURN;}
        break;
      case IF:
        IF();
         jjtree.closeNodeScope(jjtn000, true);
         jjtc000 = false;
         {if (true) return Tok.IF;}
        break;
      case ELSE:
        ELSE();
           jjtree.closeNodeScope(jjtn000, true);
           jjtc000 = false;
           {if (true) return Tok.ELSE;}
        break;
      case RESTO:
        RESTO();
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {if (true) return Tok.RESTO;}
        break;
      case READ:
        READ();
           jjtree.closeNodeScope(jjtn000, true);
           jjtc000 = false;
           {if (true) return Tok.READ;}
        break;
      case WRITE:
        WRITE();
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {if (true) return Tok.WRITE;}
        break;
      case NUMERO:
        NUMERO();
             jjtree.closeNodeScope(jjtn000, true);
             jjtc000 = false;
             {if (true) return Tok.NUMERO;}
        break;
      case STRING:
        STRING();
             jjtree.closeNodeScope(jjtn000, true);
             jjtc000 = false;
             {if (true) return Tok.STRING;}
        break;
      case IDENTIFICADOR:
        IDENTIFICADOR();
                    jjtree.closeNodeScope(jjtn000, true);
                    jjtc000 = false;
                    {if (true) return Tok.IDENTIFICADOR;}
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public ParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[22];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x10003140,0x10001100,0x10000000,0x0,0x1000,0x0,0x0,0x0,0xf0000040,0x100,0x800a040,0x0,0xf0000000,0x8008040,0x0,0x1000,0x0,0x0,0x40,0x7ffc000,0xffffffc0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x200070,0x0,0x0,0x0,0x70,0x0,0x70,0x70,0x237c00,0x3,0x0,0x300300,0x8000,0x3,0x300300,0x300000,0x0,0x300000,0x300300,0x0,0x4,0x33ff7f,};
   }

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[54];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 22; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 54; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
